External/MVC/29-Sep-2021/EmployeeManagement/Controllers/AdministrationController.cs
using BL;
using DAL.Models;
using DAL.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Presentation.Controllers
{
    [Authorize(Roles ="Admin")]
    public class AdministrationController : Controller
    {
        private readonly AccountBL _accountBL;
        public AdministrationController(AccountBL accountBL)
        {
            this._accountBL = accountBL;
        }
        public IActionResult CreateRole()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateRole(CreateRoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                var result = await _accountBL.CreateRole(model);

                if (result.Succeeded)
                {
                    return RedirectToAction("GetRoles");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(String.Empty, error.Description);
                }
            }
            return View(model);
        }

        //Get Roles
        public IActionResult GetRoles()
        {
            var roles = _accountBL.GetRoles();
            return View(roles);
        }

        //Edit Roles
        public async Task<IActionResult> EditRole(string id)
        {
            var model = await _accountBL.EditRole(id);

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditRole(EditRoleViewModel model)
        {
            var result = await _accountBL.UpdateRole(model);


            if (result.Succeeded)
            {
                return RedirectToAction("GetRoles");
            }

            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error.Description);
            }

            return View(model);
        }
        
        public async Task<IActionResult> EditUserInRole(string roleId)
        {
            ViewBag.roleId = roleId;

            var model = await _accountBL.EditUsersInRole(roleId);

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditUserInRole(List<UserRoleViewModel> model, string roleId)
        {
            if (model.Any())
            {
                var result = await _accountBL.PostUsersInRole(model, roleId);

                if (result == true)
                {
                    return RedirectToAction("EditRole", new { Id = roleId });
                }
            }

            return RedirectToAction("EditRole", new { Id = roleId });
        }

        [HttpPost]
        public async Task<IActionResult> DeleteRole(string id)
        {
            var result = await _accountBL.DeleteRole(id);

            if (result.Succeeded)
            {
                return RedirectToAction("GetRoles");
            }

            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error.Description);
            }

            return View("GetRoles");
        }
    }

}

External/MVC/29-Sep-2021/EmployeeManagement/Views/Administration/CreateRole.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewBag.Title = "Create New Role";
}

@model DAL.ViewModel.CreateRoleViewModel

@using (Html.BeginForm("CreateRole", "Administration", FormMethod.Post))
{
    <div class="container">
        <div class="row justify-content-center mt-2">
            <div class="col-8 col-sm-4">
                <h1 class="text-center">Create New Role</h1>
            </div>
        </div>
        <div class="row justify-content-center m-3">
            <div class="col-8 col-sm-4">
                <div class="form-group">
                    @Html.LabelFor(model => model.RoleName, new { @class = "control-lable" })
                    @Html.TextBoxFor(model => model.RoleName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.RoleName,"", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-8 col-sm-4">
                <input type="submit" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

External/MVC/29-Sep-2021/EmployeeManagement/Views/Administration/EditRole.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
<link href="~/css/Role.css" rel="stylesheet" />
@{
    ViewBag.Title = "Edit Role";
}

@model DAL.ViewModel.EditRoleViewModel


<div class="container">
    <div class="row justify-content-center">
        <div class="col-12 col-sm-8">
            <h1>Edit Role</h1>

            <form method="post" class="mt-3">
                <div class="form-group row">
                    <label asp-for="Id" class="col-sm-2 col-form-label"></label>
                    <div class="col-sm-10">
                        <input asp-for="Id" disabled class="form-control">
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="RoleName" class="col-sm-2 col-form-label"></label>
                    <div class="col-sm-10">
                        <input asp-for="RoleName" class="form-control">
                        <span asp-validation-for="RoleName" class="text-danger"></span>
                    </div>
                </div>

                <div asp-validation-summary="All" class="text-danger"></div>

                <div class="form-group row">
                    <div class="col-sm-10">
                        <input type="submit" class="btn btn-primary" value="Update">
                        <a asp-action="GetRoles" class="btn btn-primary">Cancel</a>
                    </div>
                </div>

                <div class="card w-75 mt-sm-5">
                    <div class="card-header bg-warning">
                        <h3>Users in this role</h3>
                    </div>
                    <div class="card-body">
                        @if (Model.Users.Any())
                        {
                            foreach (var user in Model.Users)
                            {
                                <h5 class="card-title">@user</h5>
                            }
                        }
                        else
                        {
                            <h5 class="card-title">None at the moment</h5>
                        }
                    </div>
                    <div class="card-footer bg-warning">
                        <a class="btn btn-primary" asp-controller="Administration" asp-action="EditUserInRole"
                           asp-route-roleId="@Model.Id" style="width:auto">Add or remove Users</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

External/MVC/29-Sep-2021/EmployeeManagement/Views/Administration/EditUserInRole.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
<link href="~/css/Role.css" rel="stylesheet" />
@{
    ViewBag.Title = "AssignRole";
    var roleId = ViewBag.roleId;
}

@model List<DAL.ViewModel.UserRoleViewModel>

<div class="container">
    <div class="row justify-content-center mt-sm-5">
        <div class="col-sm-8">
            <form method="post">
                <div class="card">
                    <div class="card-header bg-warning">
                        <h2>Add or remove users from this role</h2>
                    </div>
                    <div class="card-body">
                        @for (int i = 0; i < Model.Count; i++)
                        {
                            <div class="form-check m-1">
                                <input type="hidden" asp-for="@Model[i].UserId" />
                                <input type="hidden" asp-for="@Model[i].UserName" />
                                <input asp-for="@Model[i].IsSelected" class="form-check-input" />
                                <label class="form-check-label" asp-for="@Model[i].IsSelected">
                                    @Model[i].UserName
                                </label>
                            </div>
                        }
                    </div>
                    <div class="card-footer bg-warning">
                        <input type="submit" value="Update" class="btn btn-primary"
                               style="width:auto" />
                        <a asp-action="EditRole" asp-route-id="@roleId"
                           class="btn btn-primary" style="width:auto">Cancel</a>
                    </div>
                </div>
            </form>

        </div>
    </div>

</div>

External/MVC/29-Sep-2021/EmployeeManagement/Views/Administration/GetRoles.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
<link href="~/css/Role.css" rel="stylesheet" />
@{
    ViewBag.Title = "Roles";
}

@model IEnumerable<IdentityRole>

<div class="">
    <div class="container">

        <h1>All Roles</h1>

        @if (Model.Any())
        {
            <a class="btn btn-primary mb-3" style="width:auto" asp-action="CreateRole"
               asp-controller="administration">Add new role</a>

            foreach (var role in Model)
            {
                <div class="card mb-3 w-75" >
                    <div class="card-header bg-warning">
                        Role Id : @role.Id
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">@role.Name</h5>
                    </div>
                    <div class="card-footer bg-warning">
                        <form asp-action="DeleteRole" asp-route-id="@role.Id" method="post">
                            <a class="btn btn-primary" asp-controller="Administration" asp-action="EditRole"
                               asp-route-id="@role.Id">
                                Edit
                            </a>
                            <span id="confirmDeleteSpan_@role.Id" style="display:none">
                                <span>Are you sure you want to delete?</span>
                                <button type="submit" class="btn btn-danger">Yes</button>
                                <a href="#" class="btn btn-primary"
                                   onclick="confirmDelete('@role.Id', false)">No</a>
                            </span>

                            <span id="deleteSpan_@role.Id">
                                <a href="#" class="btn btn-danger"
                                   onclick="confirmDelete('@role.Id', true)">Delete</a>
                            </span>
                        </form>
                    </div>
                </div>
            }
        }
        else
        {
            <div class="card">
                <div class="card-header">
                    No roles created yet
                </div>
                <div class="card-body">
                    <h5 class="card-title">
                        Use the button below to create a role
                    </h5>
                    <a class="btn btn-primary" style="width:auto"
                       asp-controller="administration" asp-action="CreateRole">
                        Create Role
                    </a>
                </div>
            </div>
        }
    </div>
</div>


@section Scripts{ 

<script type="text/javascript">
    function confirmDelete(uniqueId, isTrue) {

        var deleteSpan = 'deleteSpan_' + uniqueId;
        var confirmDeleteSpan = 'confirmDeleteSpan_' + uniqueId;

        if (isTrue) {
            $('#' + deleteSpan).hide();
            $('#' + confirmDeleteSpan).show();
        } else {
            $('#' + deleteSpan).show();
            $('#' + confirmDeleteSpan).hide();
        }
    }
</script>
}